# Web Application Settings
web.application.url=http://www.way2automation.com/angularjs-protractor/webtables/
browser=chrome
headless=false
implicit.wait.seconds=10
page.load.timeout.seconds=10

# API Settings
api.base.url=https://dog.ceo/api
