cucumber.publish.quiet=true
cucumber.plugin=pretty, html:target/cucumber-reports/cucumber-pretty.html, json:target/cucumber-reports/CucumberTestReport.json, com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter:
cucumber.glue=com.automation.assessment.stepdefinitions
