extent.reporter.html.start=true
extent.reporter.html.out=test-output/ExtentReport/ExtentReport.html
extent.reporter.html.config=src/test/resources/extent-config.xml

#Screenshot
screenshot.dir=test-output/screenshots/
screenshot.rel.path=../screenshots/

#System Info
extent.reporter.html.systeminfo.os=Windows
extent.reporter.html.systeminfo.user=QA Automation
extent.reporter.html.systeminfo.build=1.0
extent.reporter.html.systeminfo.AppName=QA Automation Assessment
